<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.cosx</groupId>
        <artifactId>blog</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <groupId>cn.cosx</groupId>
    <artifactId>blog-auth</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>blog-auth</name>
    <description>blog-auth</description>

    <properties>
        <application.name>blog-auth</application.name>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>

        <!-- Spring Boot Web -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <!--  validation  -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>

        <dependency>
            <groupId>cn.cosx</groupId>
            <artifactId>blog-api</artifactId>
        </dependency>

        <!-- blog-sa-token -->
        <dependency>
            <groupId>cn.cosx</groupId>
            <artifactId>blog-sa-token</artifactId>
        </dependency>

        <!-- blog-base -->
        <dependency>
            <groupId>cn.cosx</groupId>
            <artifactId>blog-base</artifactId>
        </dependency>

        <!-- blog-database -->
        <dependency>
            <groupId>cn.cosx</groupId>
            <artifactId>blog-database</artifactId>
        </dependency>

        <!-- blog-cache -->
        <dependency>
            <groupId>cn.cosx</groupId>
            <artifactId>blog-cache</artifactId>
        </dependency>

        <dependency>
            <groupId>cn.cosx</groupId>
            <artifactId>blog-sms</artifactId>
        </dependency>

        <dependency>
            <groupId>cn.cosx</groupId>
            <artifactId>blog-rpc</artifactId>
        </dependency>

        <!-- blog-file - MinIO 文件存储 -->
        <dependency>
            <groupId>cn.cosx</groupId>
            <artifactId>blog-file</artifactId>
        </dependency>

        <!-- blog-config - Nacos 服务注册与发现 -->
        <dependency>
            <groupId>cn.cosx</groupId>
            <artifactId>blog-config</artifactId>
        </dependency>
        <!-- Lombok -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>

        <!--  TEST  -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <version>1.4.200</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
