server:
  port: 8009

spring:
  application:
    name: KnowEngine
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.10.10:3306/blog?rewriteBatchedStatements=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
  data:
    redis:
      host: 192.168.10.10
      port: 6379
      password: 123456
      ssl:
        enabled: true
  neo4j:
    uri: bolt://192.168.10.10:7687
    authentication:
      username: neo4j
      password: neo4j666
  redis:
    redisson:
      config: |
        singleServerConfig:
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          password: 123456
          subscriptionsPerConnection: 5
          clientName: null
          address: "redis://192.168.10.10:6379"
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 50
          connectionMinimumIdleSize: 24
          connectionPoolSize: 64
          database: 0
          dnsMonitoringInterval: 5000
        threads: 16
        nettyThreads: 32
        codec: !<org.redisson.codec.JsonJacksonCodec> {}
        transportMode: "NIO"


# LangChain4j 配置
langchain4j:
  open-ai:
    chat-model:
      api-key: @dashscope.api.key@
      model-name: qwen-max-latest
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      log-requests: true
      log-responses: true
    streaming-chat-model:
      api-key: @dashscope.api.key@
      model-name: qwen-max-latest
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      log-requests: true
      log-responses: true
  community:
    neo4j:
      await-index-timeout: 300
      auth:
        uri: bolt://192.168.10.10:7687
        user: neo4j
        password: neo4j666

elasticsearch:
  host: http://192.168.10.10:9200
  base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
  model-name: text-embedding-v4
  api-key: @dashscope.api.key@
  dimensions: 1536


neo4j:
  uri: bolt://192.168.10.10:7687
  username: neo4j
  password: neo4j666

minio:
  url: http://112.126.84.219:9000/
  accessKey: admin
  secretKey: admin123456
  bucketName: rag-test
  endpoint: http://112.126.84.219:9000
# 文件解析服务配置
mineru:
  url: https://mineru.net/api/v4/extract/task
  token: eyJ0eXBlIjoiSldUIiwiYWxnIjoiSFM1MTIifQ.eyJqdGkiOiIxNzEwMDgyMyIsInJvbCI6IlJPTEVfUkVHSVNURVIiLCJpc3MiOiJPcGVuWExhYiIsImlhdCI6MTc3NjM1MTEzNywiY2xpZW50SWQiOiJsa3pkeDU3bnZ5MjJqa3BxOXgydyIsInBob25lIjoiIiwib3BlbklkIjpudWxsLCJ1dWlkIjoiYjg4Njk5NWQtMzU2Zi00N2U1LTljNWUtYTNjMDJlYWU3NjNhIiwiZW1haWwiOiIiLCJleHAiOjE3ODQxMjcxMzd9.dQKm_52XN6GfJOei6V_9XlmECaopLvGbzO5L26NEh2RVHSRe7NeiI9A06iTIF3HfOTvDmn66NXmSRfQd4_9TAA

# 临时文件目录
temp:
  dir: /tmp/knowledge

# 禁用不需要的健康检查
management:
  health:
    elasticsearch:
      enabled: false
    neo4j:
      enabled: false

# XXL-Job 配置
xxl:
  job:
    admin:
      addresses: http://192.168.10.10:8080/xxl-job-admin # xxl-job-admin 地址，记得改成你自己的
    accessToken: default_token
    executor:
      appname: konwledgeExecutor # 执行器名称
